Feature/add intro
Argeniss-Software/rolaguard_frontend pull request #152
Opened 2021-12-14 14:20 UTC by FauDavid

Add a quick start guide. The system must be capable of making an interactive tour (tour) guiding the user to take the first steps to activate the operation of the system.

2022-01-12 14:31 UTC, AgustinSpahn requested changes
Looks good to me!

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/notifications-preferences.component.js
> +                            style={{ margin: "20px" }}
Styles could be set in a css file

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: "This button can allow you to open a form to add a new data source",
"This button allows you to open a form to add a new data source"

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `This section can allow you to configure the notifications of the system.`,
`This section allows you to configure the system notifications.`

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `These switches can allow you to select which data sources should generate notifications.`,
`These switches allow you to select which data sources should generate notifications.` (maybe "send notifications?")

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `These switches can allow you to configure the type of notifications to receive: push or email notifications.`,
remove "can"

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `This section displays statistics about the existing devices on the network. Also, you can use the filters or search bar. It shows graphs by status, flow messages and signal strength. The
`[...] The list allows you to interact with its items by clicking on them.`

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `This section lists the existing devices on the network. Also, you can use the filters or search bar. It shows graphs by vendor, data source and importance.The list can allow you to inter
same as last one

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `This section displays the existing alerts on the system. Also, you can use the filters or search bar. It shows graphs by risk, description and data source. The list can allow you to inte
same as last one

2022-01-12 14:31 UTC, AgustinSpahn commented on src/components/tour/steps-dashboard.component.js
> +      text: `This section displays the current issues on the network. While an alert is a specific event in time that can affect the network, an issue is a problem/vulnerability that is persistent. A
same as last one

2022-01-13 13:53 UTC, AgustinSpahn approved these changes, later dismissed

2022-01-13 13:54 UTC, AgustinSpahn commented
Looks good to me!

2022-01-14 17:01 UTC, cyones approved these changes

2022-01-14 17:01 UTC, merged