Geolocation circles aruond gateways and minor fixes
Argeniss-Software/rolaguard_frontend pull request #62
Opened 2020-09-16 17:41 UTC by miguelstorani

![image](https://user-images.githubusercontent.com/27182260/93372676-962bf700-f82a-11ea-84e4-6727640d2b9b.png)
![image](https://user-images.githubusercontent.com/27182260/93372714-a643d680-f82a-11ea-8aca-51fd211edaa5.png)

2020-09-16 18:49 UTC, cpfarher commented on src/components/utils/geolocation/geolocation.component.js
> +        const key = Object.keys(gw)[0];
Object.keys(gw) always exists? and is an array with almost one element?

2020-09-16 18:50 UTC, cpfarher commented on src/components/utils/geolocation/geolocation.component.js
> +    <div style={{ width: "100%", height: "200px" }}>
I think is better to change the height to 100% and manage the width and height outside the component

2020-09-16 18:51 UTC, cpfarher commented on src/components/utils/geolocation/geolocation.component.js
> +                  radius={2000}
you do not need to change this now, but maybe it is good to pass as props

2020-09-16 18:56 UTC, cpfarher requested changes
About all comments, the only that is mandatory to change I think is the height of the geolocation component. This component is used it in other sections of the web and we need to fit to the parent div.
About the other comments, if it will bring spent much time, it's ok to planified the changes for the future

2020-09-16 19:47 UTC, miguelstorani commented on src/components/utils/geolocation/geolocation.component.js
> +        const key = Object.keys(gw)[0];
Yes, it does always exists. It is an object with only one element.
![image](https://user-images.githubusercontent.com/27182260/93385235-579f3800-f83c-11ea-8435-43af69b569cd.png)

2020-09-17 18:06 UTC, cpfarher approved these changes
LGTM!

2020-09-17 18:06 UTC, merged