timeline alerts graph
Argeniss-Software/rolaguard_frontend pull request #64
Opened 2020-09-17 18:15 UTC by cpfarher

2020-09-17 18:18 UTC, cpfarher commented on src/components/visualizations/timeline-graph.component.js
> +     */
This is useful for future. I prefer to keep on the code because there is a bug on vis js and we can not used it right now, but maybe we can used in a near future...

2020-09-17 19:34 UTC, miguelstorani requested changes
We should check the way the timeline's tooltips are generated. There should be a better way to do it rather that storing html code inside a string. Also, because the http request might be heavyweight on the backend we should catch timeout errors that may occur.

2020-09-17 19:34 UTC, miguelstorani commented on src/components/utils/show-asset-info/alert-timeline-graph.component.js
> +    });
We should check if the response status is 200 before setting the state. Use HttpStatus from "http-status-codes".

2020-09-17 19:34 UTC, miguelstorani commented on src/components/utils/show-asset-info/alert-timeline-graph.component.js
> +            </div>`;
We should check that this won't be a vector attack for xss. At the moment it doesn't look like there is a xss vulnerability, but we have to be aware of this issue when making changes here. Maybe we can put some comments in the code explaining the situation.

2020-09-18 13:12 UTC, miguelstorani requested changes

2020-09-18 13:12 UTC, miguelstorani commented on src/components/utils/show-asset-info/alert-timeline-graph.component.js
> +        return sanitizeHtml(`
Are you sure that this will work?

2020-09-18 14:01 UTC, miguelstorani approved these changes
LGTM

2020-09-18 14:01 UTC, merged