360 network overview and inventory changes
Argeniss-Software/rolaguard_frontend pull request #68
Opened 2020-09-22 20:48 UTC by cpfarher

2020-09-22 20:51 UTC, cpfarher commented
You are going to see some comments in the code that I left them on purpose as they are future features to implement (add modal, filters, etc).
Also keep in mind that the comments are not showed on the final dev web page because babel / webpack takes care of removing them if it is correctly set it up.

2020-09-23 11:42 UTC, miguelstorani requested changes
There are several changes, maybe not all of them make sense, address those that really matter and send it for another review (please do not force push the changes).

2020-09-23 11:42 UTC, miguelstorani commented on src/components/resource-usage/resource-usage-modal.component.js
> +                            .format("dddd, MMMM Do, YYYY h:mm:ss A")}
Why isn't used the global config?

2020-09-23 11:42 UTC, miguelstorani commented on src/components/utils/show-asset-info/associated-asset-inventory-show.component.js
> +// import DateFilterBar from "./date-filter-bar.component";
Delete comment

2020-09-23 11:42 UTC, miguelstorani commented on src/components/utils/show-asset-info/associated-asset-inventory-show.component.js
> +  */
Delete comment

2020-09-23 11:42 UTC, miguelstorani commented on src/components/utils/show-asset-info/associated-asset-inventory-show.component.js
> +  };*/
delete comment

2020-09-23 12:12 UTC, cpfarher commented on src/components/resource-usage/show-packets-statistics.component.js
> +      : parseFloat(data.packets_up.percentage.toFixed(1)),
yes always defined, it comes for a pre process data outside component

2020-09-23 12:13 UTC, cpfarher commented on src/components/utils/show-asset-info/alert-timeline-graph.component.css
> +}*/
I think is better to keep this coment because we need to test the feature. If it is not approved for the responsible we need to go back :|

2020-09-23 12:13 UTC, cpfarher commented on src/components/utils/show-asset-info/alert-timeline-graph.component.css
> +}*/
I think is better to keep this coment because we need to test the feature. If it is not approved for the responsible we need to go back :|

2020-09-23 12:16 UTC, cpfarher commented on src/components/resource-usage/resource-usage-modal.component.js
> +                            .format("dddd, MMMM Do, YYYY h:mm:ss A")}
because it isn't on the form mm/dd/yy.... and this kind of format is the same for any country

2020-09-23 12:18 UTC, cpfarher commented on src/components/utils/show-asset-info/resource-usage/packets-graph-component.js
> +      {(isLoading && _.isEmpty(resourceUsagePacketList)) && (
This component work by ajax or by props. So when  work with props, do not need loading nothing, so the setIsLoading always is false.

2020-09-23 12:20 UTC, cpfarher commented on src/components/utils/show-asset-info/alert-timeline-graph.component.js
> +        content: " ", //_.truncate(_.get(e, "type.name", "N/A"), { length: 14 }),
I think is better to keep this coment because we need to test the feature. If it is not approved for the responsible we need to go back :|

2020-09-23 12:41 UTC, miguelstorani approved these changes
LGTM

2020-09-23 12:41 UTC, miguelstorani commented on src/components/utils/show-asset-info/alerts-show.component.js
> +                      showAsLink={type === "gateway" ? false : true}
Is there a reason behind this way of doing it? Wouldn't it be better to just make `!(type === "gateway")`

2020-09-23 13:01 UTC, miguelstorani approved these changes

2020-09-23 13:01 UTC, merged