Add "not available" to empty fields in alert details, packets involved and inventory section on asset360
Argeniss-Software/rolaguard_frontend pull request #88
Opened 2020-10-08 17:23 UTC by miguelstorani

2020-10-08 17:47 UTC, cpfarher requested changes

2020-10-08 17:47 UTC, cpfarher commented on src/components/details.alert.modal.component.js
> +          <Table.Cell width="3"
```suggestion
          <Table.Cell width={3}
```

2020-10-08 17:47 UTC, cpfarher commented on src/components/details.alert.modal.component.js
> +            style={{ "borderTop": "1px solid lightgray !important" }}><i>{header}</i></Table.Cell>
```suggestion
            style={{borderTop: "1px solid lightgray !important" }}><i>{header}</i></Table.Cell>
```

2020-10-08 17:47 UTC, cpfarher commented on src/components/details.alert.modal.component.js
> +            style={{ "borderTop": "1px solid lightgray !important" }}><i>{header}</i></Table.Cell>
Are you sure to put the "!important"... I think it is unnecessary on "inline style" because it has the major importance than class css styles or others...

2020-10-08 17:47 UTC, cpfarher commented on src/components/details.alert.modal.component.js
> +          <Table.Cell width="3" className={(parameterToUpper && value) ? "technical-details-table-row-right upper" : "technical-details-table-row-right"}>{value ? <b>{value}</b> : <i style={{ color:
```suggestion
          <Table.Cell width={3} className={`technical-details-table-row-right ${(parameterToUpper && value) ? "upper" : ""}`}>{value ? <b>{value}</b> : <i style={{ color: "gray", opacity:"0.8"}}>not available</i>}</Table.Cell>
```

2020-10-08 17:47 UTC, cpfarher commented on src/components/utils/show-asset-info/inventory-show.component.js
> +                        </i>
maybe you can define a function or a const with this value and replace for re used it...

2020-10-08 18:49 UTC, miguelstorani commented on src/components/utils/show-asset-info/inventory-show.component.js
> +                        </i>
I was thinking on doing that globally. Should I do it that way?

2020-10-13 13:46 UTC, cpfarher approved these changes

2020-10-13 14:00 UTC, merged